/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lazy

import kotlin.test.Test
import kotlin.test.assertNotNull

class DearLazyTest {
/*    @Test fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }*/
}
